# Generated by Django 4.2.7 on 2025-11-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language_prefs',
            field=models.CharField(default='mixed', max_length=20),
        ),
    ]
