# Generated by Django 4.2.7 on 2025-11-05 10:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('nudity', 'Nudity'), ('harassment', 'Harassment'), ('spam', 'Spam'), ('underage', 'Underage Suspicion'), ('other', 'Other')], max_length=20)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('action_taken', models.CharField(choices=[('none', 'No Action'), ('warning', 'Warning'), ('ban', 'Ban User')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reported_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
