# Generated by Django 4.2.7 on 2025-11-05 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vibe_tag', models.CharField(choices=[('music', 'Music'), ('tech', 'Tech'), ('jokes', 'Jokes'), ('relationships', 'Relationships'), ('travel', 'Travel'), ('random', 'Random')], default='random', max_length=20)),
                ('language', models.CharField(default='mixed', max_length=10)),
                ('is_visitor', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'match_queue',
                'ordering': ['created_at'],
            },
        ),
    ]
