# Generated by Django 4.2.7 on 2025-11-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchqueue',
            name='language',
            field=models.CharField(default='mixed', max_length=20),
        ),
    ]
