# Generated by Django 4.2.7 on 2025-11-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='language',
            field=models.CharField(default='mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting for Match'), ('active', 'Active'), ('ended', 'Ended'), ('flagged', 'Flagged')], default='waiting', max_length=20),
        ),
    ]
