# Generated by Django 4.2.7 on 2025-11-11 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0005_contactexchange'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconnectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fuse_moment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconnect_requests', to='chat.fusemoment')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_reconnect_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_reconnect_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reconnect_requests',
                'unique_together': {('fuse_moment', 'sender')},
            },
        ),
    ]
