# Generated by Django 4.2.7 on 2025-11-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_reconnectrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReconnectRequest',
        ),
    ]
